/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition


    export interface MarketStatus  {
        api_timestamp? : Date
        status? : string
        options? : MarketStatusOptions
        urls? : Array<string>
        products? : Array<string>
        market_area_id? : string
        delivery_area_id? : string
        session_id? : number
        logged_in_since? : Date
        heartbeat_as_of? : Date
        heartbeat_content? : string
        messages? : Array<string>
    }
    export interface Message  {
        message_id? : string
        api_timestamp? : Date
        category? : string
        message_class? : string
        content_type? : string
        correlation_id? : string
        direction? : string
        group_id? : string
        group_sequence? : string
        content? : MessageContent
    }
    export interface OrderBooks  {
        products? : Array<SwaggerInlineType3>
        contracts? : Array<SwaggerInlineType4>
    }
    export interface ProductInformation  {
        product_name? : string
        delivery_area? : string
        price_currency? : string
        quantity_unit? : string
    }
    export interface OrderBook  {
        product? : string
        product_details? : OrderBookProductDetails
        delivery_area? : string
        price_currency? : string
        quantity_unit? : string
        contracts? : Array<SwaggerInlineType6>
    }
    export interface OwnOrder  {
        order_id? : number
        api_timestamp? : Date
        state? : string
        delivery_area? : string
        last_change_timestamp? : Date
        buy? : boolean
        sell? : boolean
        side? : string
        contract_id? : number
        contract_name? : string
        delivery_start? : Date
        delivery_end? : Date
        clOrdrId? : string
        txt? : string
        price? : number
        quantity? : number
        action? : string
        details? : OwnOrderDetails
    }
    export interface PublicTrade  {
        trade_id? : number
        api_timestamp? : Date
        exec_time? : Date
        contract_id? : number
        price? : number
        quantity? : number
    }
    export interface Trade  {
        trade_id? : number
        state? : string
        delivery_area? : string
        api_timestamp? : Date
        exec_time? : Date
        buy? : boolean
        sell? : boolean
        buy_order_id? : number
        buy_delivery_area? : string
        buy_clOrderId? : string
        buy_txt? : string
        buy_user_code? : string
        buy_member_id? : string
        buy_aggressor_indicator? : string
        sell_order_id? : number
        sell_delivery_area? : string
        sell_clOrderId? : string
        sell_txt? : string
        sell_user_code? : string
        sell_member_id? : string
        sell_aggressor_indicator? : string
        contract_id? : number
        contract_name? : string
        delivery_start? : Date
        delivery_end? : Date
        price? : number
        quantity? : number
        trade_details? : TradeTradeDetails
        contract_details? : TradeContractDetails
    }
    export interface ContractHistoryItem  {
        as_of? : Date
        revisionNo? : number
        vwap? : number
        best_bid_price? : number
        best_bid_quantity? : number
        best_ask_price? : number
        best_ask_quantity? : number
        last_price? : number
        last_quantity? : number
        total_quantity? : number
        auction_price? : number
        high? : number
        low? : number
        signals? : Array<SwaggerInlineType10>
        trades? : Array<SwaggerInlineType11>
    }
    export interface ContractItem  {
        product? : string
        contract_id? : number
        revision_no? : number
        state? : string
        name? : string
        delivery_start? : Date
        delivery_end? : Date
        contract_details? : ContractItemContractDetails
        relative_position? : number
        absolute_position? : number
        signals? : Array<SwaggerInlineType13>
    }
    export interface Contract  {
        product? : string
        contract_id? : number
        state? : string
        name? : string
        revision_no? : number
        delivery_start? : Date
        delivery_end? : Date
        best_bid_price? : number
        best_bid_quantity? : number
        best_ask_price? : number
        best_ask_quantity? : number
        last_price? : number
        last_quantity? : number
        total_quantity? : number
        auction_price? : number
        high? : number
        low? : number
        contract_details? : ContractContractDetails
        orderbook_details? : ContractOrderbookDetails
        relative_position? : number
        absolute_position? : number
        last_trade_time? : Date
        signals? : Array<SwaggerInlineType16>
    }
    export interface Orders  {
        bid? : Array<SwaggerInlineType17>
        ask? : Array<SwaggerInlineType18>
    }
    export interface OrderBookEntry  {
        order_id? : number
        order_entry_time? : Date
        price? : number
        quantity? : number
    }
    export interface UpdateStatus  {
        orderModType? : string
        inclPreArranged? : boolean
        prodName? : Array<string>
    }
    export interface OrderModify  {
        action? : string
        validityRes? : string
        validityDate? : Date
        type? : string
        txt? : string
        ordrExeRestriction? : string
        quantity? : number
        displayQty? : number
        price? : number
        clOrdrId? : string
        ppd? : number
    }
    export interface OrderEntry  {
        delivery_area? : string
        side? : string
        prod? : string
        quantity? : number
        price? : number
        displayQty? : number
        contractId? : number
        contractName? : string
        clOrdrId? : string
        clearingAcctType? : string
        ordrExeRestriction? : string
        preArranged? : boolean
        preArrangedAcct? : string
        type? : string
        validityRes? : string
        state? : string
        validityDate? : Date
        txt? : string
        ppd? : number
        dlvryStart? : Date
        dlvryEnd? : Date
    }
    export interface Credentials  {
        password? : string
    }
    export interface MarketOptions  {
        relative_position_limit? : number
        absolute_position_limit? : number
    }
    export interface Notification  {
        msg_id? : number
        type? : string
        code? : number
        epex_timestamp? : Date
        api_timestamp? : Date
        text? : string
        severity? : string
    }
    export interface Signal  {
        id? : string
        source? : string
        received_at? : Date
        revision? : number
        delivery_start? : Date
        delivery_end? : Date
        value? : SignalValue
    }
    export interface LogEntry  {
        id? : string
        received? : Date
        text? : string
        as_of? : Date
        category? : string
        severity? : string
    }
    export interface ApiKeyDescription  {
        name? : string
        epex_password? : string
        can_trade? : boolean
        can_signal? : boolean
    }
    export interface ApiKey  {
        name? : string
        value? : string
    }
    export interface BulkSignal  {
        id? : string
        source? : string
        value? : BulkSignalValue
        delivery_start? : Date
        delivery_end? : Date
    }
    export interface BulkSignalResponse  {
        id? : string
        source? : string
        status? : string
        status_text? : string
    }
    export interface ErrorResponse  {
        message? : string
    }
    export interface MarketStatusOptions  {
        relative_position_limit? : number
        absolute_position_limit? : number
    }
    export interface MessageContent  {
    }
    export interface OrderBookProductDetails  {
    }
    export interface OwnOrderDetails  {
    }
    export interface TradeTradeDetails  {
    }
    export interface TradeContractDetails  {
    }
    export interface ContractItemContractDetails  {
    }
    export interface ContractContractDetails  {
    }
    export interface ContractOrderbookDetails  {
    }
    export interface SignalValue  {
    }
    export interface BulkSignalValue  {
    }
